version: "3"

networks:
  external:
    external: true

services:
#loki est un gestionnaire centralisé de logs
  loki:
    image: harbinfo.iutmontp.univ-montp2.fr/proxy_dockerhub/grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - external

  #promtail permet de faire remonter les logs de la machine locale dans le loki
  promtail:
    image: harbinfo.iutmontp.univ-montp2.fr/proxy_dockerhub/grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - external

#grafana est l'interface graphique qui permet d'interroger l'API de loki
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: harbinfo.iutmontp.univ-montp2.fr/proxy_dockerhub/grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - external
